apiVersion: template.openshift.io/v1
kind: Template
metadata:
   name: mytemplate
   annotations:
      description: "Description"
objects:
- apiVersion: v1
kind: Pod
metadata:
   name: myapp
spec:
   containers:
- env:
    - name: MYAPP_CONFIGURATION
      value: ${MYPARAMETER}
image: myorganization/myapplication
name: myapp
ports:
- containerPort: 80
  protocol: TCP
parameters:
- description: Myapp configuration data
  name: MYPARAMETER
  required: true
labels:
mylabel: myapp
